# 苦力怕论坛 自动签到
# GitHub: https://github.com/xyz8848/KLPBBS_auto_sign_in

name: 'Format Code'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install black

      - name: Format Python code
        run: black .

      - name: Check if local and remote branches are the same
        run: |
          local_branch=$(git symbolic-ref --short HEAD)
          remote_branch=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})
          if [ "$local_branch" = "$remote_branch" ]; then
            echo "本地分支和远程分支一致，不执行提交操作。"
            exit 0
          fi

      - name: Commit formatted code
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Auto-format code"
          git push
